"""PyDeequ translator — emits a runnable Python script of Check method calls."""

import os
from collections.abc import Callable

from fidu.core.rule_filter import filter_executable_rules

RuleHandler = Callable[[dict], str | None]


class DeequTranslator:
    def __init__(self) -> None:
        self._handlers: dict[str, RuleHandler] = {
            "not_null": lambda r: f"isComplete('{r.get('column')}')",
            "unique": lambda r: f"isUnique('{r.get('column')}')",
            "accepted_values": lambda r: (
                f"isContainedIn('{r.get('column')}', {list(r.get('values', []))!r})"
            ),
            "min_value": lambda r: (
                f"hasMin('{r.get('column')}', lambda x: x >= {r['value']})"
            ),
            "max_value": lambda r: (
                f"hasMax('{r.get('column')}', lambda x: x <= {r['value']})"
            ),
            "between": lambda r: (
                f"satisfies('{r.get('column')} >= {r['min_value']} AND "
                f"{r.get('column')} <= {r['max_value']}', '{r['name']}')"
            ),
            "row_count_min": lambda r: f"hasSize(lambda x: x >= {r['value']})",
            "row_count_max": lambda r: f"hasSize(lambda x: x <= {r['value']})",
        }

    def translate_rule(self, rule: dict) -> str | None:
        handler = self._handlers.get(rule["type"])
        return handler(rule) if handler else None

    def translate_dataset(self, dataset_rules: dict) -> str:
        lines = [
            "# Auto-generated by Enterprise DQ Kit",
            "from pydeequ.checks import Check, CheckLevel",
            "from pydeequ.verification import VerificationSuite",
            "",
            f"check = Check(spark, CheckLevel.Error, '{dataset_rules['dataset']}_checks')",
        ]
        for rule in filter_executable_rules(dataset_rules.get("rules", [])):
            expr = self.translate_rule(rule)
            lines.append(
                f"check = check.{expr}"
                if expr
                else f"# Unsupported rule: {rule['name']} ({rule.get('type')})"
            )
        lines += [
            "",
            "result = VerificationSuite(spark).onData(df).addCheck(check).run()",
            "print(result.status)",
        ]
        return "\n".join(lines) + "\n"

    def write_artifact(self, dataset_rules: dict, output_dir: str) -> str:
        os.makedirs(output_dir, exist_ok=True)
        path = os.path.join(output_dir, f"{dataset_rules['dataset']}_deequ_check.py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.translate_dataset(dataset_rules))
        return path
